name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Download JDK 21-ea
      run: wget https://download.java.net/java/early_access/jdk21/22/GPL/openjdk-21-ea+22_linux-x64_bin.tar.gz -O openjdk-21-ea+22_linux-x64_bin.tar.gz
    - name: Unzip JDK 21-ea
      run: mkdir 21-ea && tar -xvf openjdk-21-ea+22_linux-x64_bin.tar.gz -C 21-ea/
    - name: jlink 21-ea
      run: cd 21-ea && jlink --add-modules java.base,jdk.compiler --no-header-files --no-man-pages --strip-debug --output 21-ea-min
    - name: Zip up result
      run: zip -r 21-ea-min.zip 21-ea-min